apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appsecret }}
data:
  {{- $files := .Files }}
  {{- range .Values.secrets }}
    {{- if eq .namespace "default" }}
    {{ .name }}: |-
      {{ ($files.Get .file) | b64enc }}
    {{- end }}
  {{- end }}
