theme: just-the-docs
# remote_theme: pmarsceill/just-the-docs
logo: "openidl_color.png"
title: openIDL
email: kens@aaisonline.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the openIDL documentation site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "openidl.org"
aux_links:
  "About":
    - "//openidl.lfprojects.linuxfoundation.org/"
  "GitHub Code":
    - "//github.com/openidl-org/openidl-main"
  "GitHub Pages":
    - "//github.com/openidl-org/openidl-main/tree/gh-pages"
