global:
  clusterurl: aais.test.io
  appsecret: apps-secret
  datacallapp:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-app-service
    ingresshostname: data-call-app-aais.test.io
  carrierui:
    install: true
    servicename: carrier-ui-service
    port: 8080
    targetport: 8080
  insurancedatamanager:
    install: true
    port: 8080
    targetport: 8080
    servicename: insurance-data-manager-service
  datacallprocessor:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-processor-service
  mongodb:
    install: true
    servicename: mongodb-service
  upload:
    install: true
    port: 80
    targetport: 80
    servicename: upload-service