global:
  clusterurl: aais.test.io
  appsecret: apps-secret
  datacallapp:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-app-service
    ingresshostname: data-call-app-aais.test.io
  ui:
    install: true
    servicename: ui-service
    port: 8080
    targetport: 8080
  datacallmoodlistener:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-mood-listener-service
  transactionaldataeventlistener:
    install: true
    port: 8080
    targetport: 8080
    servicename: transactional-data-event-listener-service
  mongodb:
    install: true
    servicename: mongodb-service