global:
  clusterurl: aaisanalyticsdemo.com
  appsecret: apps-secret
  datacallapp:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-app-service
    ingressenabled: false
    ingresshostname: data-call-app-service.analytics.dev.internal.aaisanalyticsdemo.com
    publicingresshostname: data-call-app-service.analytics.dev.aaisanalyticsdemo.com
  ui:
    install: true
    servicename: ui-service
    port: 8080
    targetport: 8080
    ingressenabled: false
    ingresshostname: openidl.analytics.dev.aaisanalyticsdemo.com
  datacallmoodlistener:
    install: true
    port: 8080
    targetport: 8080
    servicename: data-call-mood-listener-service
  transactionaldataeventlistener:
    install: true
    port: 8080
    targetport: 8080
    servicename: transactional-data-event-listener-service