#GitHub Actions to deploy openidl application using HELM upgrade 
#It requires the EKS cluster public access turned ON 

#Prerequisites: IAM User (access key, secret key), IAM Role (with its external_id setup), EKS region, EKS cluster name. 
# Note: All these prereqs are provisioned part of AWS resources provisioning part of gitactions+terraform deployment. 
# It is required to inspect the AWS resources and gather the information to setup and enable this gitactions. 
# Setup the following secrets in github as environment secrets under environment named "dev-analytics"
# 1. eks_admin_access_key 
# 2. eks_admin_secret_key 
# 3. eks_sm_region 
# 4. eks_external_id 
# 5. eks_cluster_name 
# 6. eks_admin_role

#Authors: Rajesh Sanjeevi & Sandeep Pulluru 
#Version: v1.0 

name: Deploy openIDL dev-analytics
on:
  push:
    branches:
      - 'git-actions-helm'
    paths:
      - 'openidl-k8s/global-values-dev-analytics.yaml'

defaults:
  run:
    shell: bash

jobs:
  deploy-openidl-app:
    environment: dev-analytics

    name: Deploy openIDL application on dev-analytics
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS CLI with credentials
      uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
      with:
        aws-access-key-id: ${{ secrets.eks_admin_access_key }}
        aws-secret-access-key: ${{ secrets.eks_admin_secret_key }}
        aws-region: ${{ secrets.eks_sm_region }}
        role-to-assume: ${{ secrets.eks_admin_role }}
        role-external-id: ${{ secrets.eks_external_id }}
        role-duration-seconds: 3600 # session valid for 30 minutes
        role-session-name: git-actions 

    - name: Checkout Code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Setup kube-config
      run: |
        aws eks update-kubeconfig --region ${{ secrets.eks_sm_region }} --name ${{ secrets.eks_cluster_name }}
    - name: Deploy openIDL app using helm
      run: |
        helm upgrade --install dev-analytics ./openidl-k8s -f ./openidl-k8s/global-values-dev-analytics.yaml -n openidl --set global.datacallapp.ingressenabled=true --set global.utilities.ingressenabled=true  --set global.ui.ingressenabled=true --set global.secrets.install=false
